"""
Django settings for emdcbackend project.

Generated by 'django-admin startproject' using Django 5.1.1.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------
# Load backend/emdcbackend/.prod.env
# ---------------------------------------------------------------------
env_path = BASE_DIR / ".prod.env"
if env_path.exists():
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            v = v.strip()
            if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                v = v[1:-1]
            os.environ.setdefault(k.strip(), v)

# ---------------------------------------------------------------------
# Core security / debug
# ---------------------------------------------------------------------
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

DEBUG = os.getenv("DEBUG", "0").lower() in ("1", "true", "yes")

_allowed_hosts_env = os.getenv("ALLOWED_HOSTS")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
else:
    # Default hosts for local + production
    ALLOWED_HOSTS = [
        "0.0.0.0",
        "localhost",
        "127.0.0.1",
        "emdc-django-api",
        "api.emdcresults.com",
        "emdcresults.com",
        "www.emdcresults.com",
    ]

# ---------------------------------------------------------------------
# Helper for env bools
# ---------------------------------------------------------------------
def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.lower() in ("1", "true", "yes")

# ---------------------------------------------------------------------
# Cookie / session / CSRF configuration
# ---------------------------------------------------------------------
SESSION_COOKIE_AGE = 10800  # 3 hours in seconds

# With frontend on www.emdcresults.com and backend on api.emdcresults.com,
# cookies are first-party again.
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", default=not DEBUG)

# CSRF cookie must be readable by JS so the frontend can send it in X-CSRFToken
SESSION_COOKIE_HTTPONLY = _env_bool("SESSION_COOKIE_HTTPONLY", default=True)
CSRF_COOKIE_HTTPONLY = _env_bool("CSRF_COOKIE_HTTPONLY", default=False)

# Scope cookies to the whole emdcresults.com domain in production
if not DEBUG:
    SESSION_COOKIE_DOMAIN = ".emdcresults.com"
    CSRF_COOKIE_DOMAIN = ".emdcresults.com"

# ---------------------------------------------------------------------
# CORS / CSRF domains
# ---------------------------------------------------------------------
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    # local dev
    "http://localhost:7001",
    "http://127.0.0.1:7001",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    # production frontend
    "https://emdcresults.com",
    "https://www.emdcresults.com",
]

# Always explicitly trust these origins for CSRF
CSRF_TRUSTED_ORIGINS = [
    # local dev
    "http://localhost:7001",
    "http://127.0.0.1:7001",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    # production (frontend + backend)
    "https://emdcresults.com",
    "https://www.emdcresults.com",
    "https://api.emdcresults.com",
]

# ---------------------------------------------------------------------
# Installed apps
# ---------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "emdcbackend",
]

# ---------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "emdcbackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "emdcbackend.wsgi.application"

# ---------------------------------------------------------------------
# Database (Postgres via env)
# ---------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# ---------------------------------------------------------------------
# Password validation
# ---------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "emdcbackend.auth.password_validators.UppercasePasswordValidator",
    },
    {
        "NAME": "emdcbackend.auth.password_validators.LowercasePasswordValidator",
    },
    {
        "NAME": "emdcbackend.auth.password_validators.SpecialCharacterPasswordValidator",
    },
]

# ---------------------------------------------------------------------
# i18n / timezone
# ---------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Chicago"
USE_I18N = True
USE_TZ = True

# ---------------------------------------------------------------------
# Static files
# ---------------------------------------------------------------------
STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Return JSON on CSRF failures (for Postman/browser API calls)
CSRF_FAILURE_VIEW = "emdcbackend.views.errors.csrf_failure"

# ---------------------------------------------------------------------
# Email (Resend via env)
# ---------------------------------------------------------------------
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.resend.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "resend")
EMAIL_HOST_PASSWORD = os.environ.get("RESEND_API_KEY")

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", "EMDC Contest <noreply@emdcresults.com>"
)
