# Generated by Django 5.1.1 on 2025-09-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0005_remove_specialaward_team_specialaward_teamid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('isSubmitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MapAwardToContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestid', models.IntegerField()),
                ('awardid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapBallotToVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballotid', models.IntegerField()),
                ('voteid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapTeamToVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamid', models.IntegerField()),
                ('voteid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MapVoteToAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awardid', models.IntegerField()),
                ('voteid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votedteamid', models.IntegerField()),
            ],
        ),

        # 🔧 FIXED DEFAULTS BELOW

        migrations.AddField(
            model_name='judge',
            name='championship',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judge',
            name='redesign',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialaward',
            name='isJudge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teams',
            name='championship_score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='redesign_score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='mapscoresheettoteamjudge',
            name='sheetType',
            field=models.IntegerField(choices=[(1, 'Presentation'), (2, 'Journal'), (3, 'Machinedesign'), (4, 'Runpenalties'), (5, 'Otherpenalties'), (6, 'Redesign'), (7, 'Championship')]),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='sheetType',
            field=models.IntegerField(choices=[(1, 'Presentation'), (2, 'Journal'), (3, 'Machinedesign'), (4, 'Runpenalties'), (5, 'Otherpenalties'), (6, 'Redesign'), (7, 'Championship')]),
        ),
    ]
