# Generated by Django 4.2.16 on 2025-11-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0006_teams_advanced_to_championship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSharedPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(2, 'ORGANIZER'), (3, 'JUDGE')], unique=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
