# Generated by Django 4.2.16 on 2025-09-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0006_ballot_mapawardtocontest_mapballottovote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='championship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='judge',
            name='journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='judge',
            name='mdo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='judge',
            name='otherpenalties',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='judge',
            name='presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='judge',
            name='redesign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='judge',
            name='runpenalties',
            field=models.BooleanField(default=False),
        ),
    ]
