# Generated by Django 4.2.16 on 2025-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0007_alter_judge_championship_alter_judge_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='school_name',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
