# Generated by Django 4.2.16 on 2025-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0008_teams_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='school_name',
            field=models.CharField(default='MNSU', max_length=255),
        ),
    ]
