# Generated by Django 4.2.16 on 2025-10-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0009_alter_teams_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='advanced_to_championship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teams',
            name='championship_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
