# Generated by Django 4.2.16 on 2025-10-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0011_judgeclusters_is_active_cluster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='preliminary_journal_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='preliminary_machinedesign_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='preliminary_penalties_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='preliminary_presentation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='preliminary_total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
