# Generated by Django 4.2.16 on 2025-10-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0012_teams_preliminary_journal_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='championship_machinedesign_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='championship_penalties_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='championship_presentation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='redesign_journal_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='redesign_machinedesign_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='redesign_penalties_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='redesign_presentation_score',
            field=models.FloatField(default=0.0),
        ),
    ]
