# Generated by Django 4.2.16 on 2025-10-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0013_teams_championship_machinedesign_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='field18',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field21',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field22',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field23',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field26',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field27',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field28',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field29',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field30',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field31',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field32',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field33',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field34',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field35',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field36',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field37',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field38',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field39',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field40',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field41',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='field42',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='championship_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='teams',
            name='redesign_score',
            field=models.FloatField(default=0.0),
        ),
    ]
