# Generated by Django 4.2.16 on 2025-10-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0016_clean_field9_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='field9',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
