# Generated by Django 4.2.16 on 2025-10-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0015_fix_field9_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='field9',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
