# Generated by Django 4.2.16 on 2025-10-27 22:56

from django.db import migrations


def clean_field9_data(apps, schema_editor):
    """Clean up field9 data by converting non-numeric values to None"""
    Scoresheet = apps.get_model('emdcbackend', 'Scoresheet')
    
    # Get all scoresheets with field9 data
    scoresheets = Scoresheet.objects.exclude(field9__isnull=True)
    
    for sheet in scoresheets:
        try:
            # Try to convert to float
            float(sheet.field9)
        except (ValueError, TypeError):
            # If conversion fails, set to None
            sheet.field9 = None
            sheet.save()


def reverse_clean_field9_data(apps, schema_editor):
    """Reverse operation - convert None back to empty string"""
    Scoresheet = apps.get_model('emdcbackend', 'Scoresheet')
    
    # Update all records where field9 is None
    Scoresheet.objects.filter(field9__isnull=True).update(field9='')


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0014_scoresheet_field18_scoresheet_field19_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_field9_data, reverse_clean_field9_data),
    ]
