# Generated by Django 4.2.16 on 2025-10-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0016_alter_scoresheet_field9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresheet',
            name='field18',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
