# Generated by Django 4.2.16 on 2025-10-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0017_fix_field18_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='championship_general_penalties_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='championship_run_penalties_score',
            field=models.FloatField(default=0.0),
        ),
    ]
