# Generated by Django 4.2.16 on 2025-10-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0018_teams_championship_general_penalties_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='redesign_journal_score',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='redesign_machinedesign_score',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='redesign_penalties_score',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='redesign_presentation_score',
        ),
    ]
