# Generated by Django 5.2.8 on 2025-11-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0021_judge_cluster_assignment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='journal_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='teams',
            name='machinedesign_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='teams',
            name='penalties_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='teams',
            name='presentation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='teams',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
