# Generated by Django 5.2.8 on 2025-11-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0022_alter_teams_journal_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='contestid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapclustertoteam',
            name='clusterid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapclustertoteam',
            name='teamid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapcontesttocluster',
            name='clusterid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapcontesttocluster',
            name='contestid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapcontesttojudge',
            name='contestid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapcontesttojudge',
            name='judgeid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapcontesttoorganizer',
            name='contestid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapcontesttoorganizer',
            name='organizerid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapcontesttoteam',
            name='contestid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapcontesttoteam',
            name='teamid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapjudgetocluster',
            name='clusterid',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mapjudgetocluster',
            name='contestid',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapjudgetocluster',
            name='judgeid',
            field=models.IntegerField(db_index=True),
        ),
    ]
